### ISSUE TITLE
Ürün detay sayfasındaki eksikler

### ISSUE THREAD

**Issue by GoktugOzturk** [GoktugOzturk/tet-gelbura#3]
/urun/addison-rampage-test-urun-deneme

Kargo Ücreti yazısının yerini ben yanlış koymuşum. Düzelteceğim.
Dİğer yerlerde hata var.
Hızlı kargo gibi ikonlar mevcut değil sanırım.
http://imgur.com/a/kyzD0

**Comment by eraysays** [comment]
Linkten kontrol edebilir miyiz? Kargo elementlerini göremedim development versiyonunda.
http://1px.co/gelbura-v2/?page=product&options=true

Üst kısımdaki indirim stili benim hatam.

**Comment by GoktugOzturk** [comment]
Sadece indirim stili kaldı. 
Gerisini düzelttim
